"""Run harness artifact types.

Every simulation run the connector executes produces a coherent artifact
bundle bound to a single run id. The harness captures stdout, stderr,
intermediate state, resource usage, and the framework's native output;
progress is surfaced to the user as *structured* reports — not raw log
dumps — so a UI can display "timestep N of M, observable X is Y" without
tailing a logfile.

The protocol document (ODD for ABMs, equivalent for other formalisms) is
also part of every run bundle — it is the primary scientific artifact of
a run, alongside the numerical results. It is generated by the plugin's
``generate_protocol`` method and stored under the run's directory.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Optional

from pydantic import BaseModel, Field


class RunStatus(str, Enum):
    PENDING = "pending"             # created, not yet started
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    TERMINATED = "terminated"       # clean termination by harness (budget, user)


class RunLayout(BaseModel):
    """Standard on-disk layout under ``root``.

    Every plugin must persist its run artifacts into this layout so the
    downstream comparator + dashboard can find them without per-framework
    logic.
    """

    root: Path
    inputs: Path
    outputs: Path
    logs: Path
    snapshots: Path
    protocol: Path
    metadata: Path

    @classmethod
    def under(cls, root: Path) -> "RunLayout":
        return cls(
            root=root,
            inputs=root / "inputs",
            outputs=root / "outputs",
            logs=root / "logs",
            snapshots=root / "snapshots",
            protocol=root / "protocol",
            metadata=root / "metadata",
        )

    def ensure(self) -> None:
        for p in (
            self.root, self.inputs, self.outputs,
            self.logs, self.snapshots, self.protocol, self.metadata,
        ):
            p.mkdir(parents=True, exist_ok=True)


class ProgressReport(BaseModel):
    """A structured progress snapshot, emitted by the plugin's ``monitor``.

    The harness surfaces these to the user/UI; raw stdout/stderr is kept in
    ``logs/`` for debugging but is NOT the progress channel.
    """

    run_id: str
    ts: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    sim_time_s: Optional[float] = Field(
        default=None,
        description="Current simulated time (not wall time).",
    )
    sim_time_horizon_s: Optional[float] = Field(
        default=None,
        description="Target end simulated time — for % completion UI.",
    )
    timestep_index: Optional[int] = None
    timestep_total: Optional[int] = None
    wall_time_elapsed_s: float = 0.0
    wall_time_estimated_remaining_s: Optional[float] = None
    memory_rss_gb: Optional[float] = None
    cpu_percent: Optional[float] = None
    observables: dict[str, float] = Field(
        default_factory=dict,
        description="Current values of scalar observables requested by the "
        "IR (keyed by Observable.id). Spatial fields and distributions are "
        "NOT reported here — they live in snapshots.",
    )
    message: str = ""


class ResourceUsage(BaseModel):
    """Summary of resource consumption over the full run."""

    wall_time_s: float
    peak_memory_gb: Optional[float] = None
    cpu_time_s: Optional[float] = None
    peak_cpu_percent: Optional[float] = None


class Artifact(BaseModel):
    """A single persisted file in a run bundle.

    Paths are stored RELATIVE to ``RunLayout.root`` so run bundles are
    relocatable.
    """

    relative_path: str
    kind: str = Field(
        description="Free-text kind tag — 'input', 'output', 'log', "
        "'snapshot', 'protocol', 'metadata'."
    )
    content_type: Optional[str] = None
    size_bytes: Optional[int] = None
    notes: str = ""


class OutputBundle(BaseModel):
    """The plugin's parsed view of a successful run's outputs.

    Produced by ``FrameworkPlugin.parse_outputs``. Raw framework outputs
    live on disk under ``RunLayout.outputs``; this bundle is the
    framework-agnostic projection the comparator consumes.
    """

    run_id: str
    # Time series keyed by Observable.id -> list of (t_s, value)
    scalar_time_series: dict[str, list[tuple[float, float]]] = Field(default_factory=dict)
    # Final-snapshot fields keyed by Observable.id -> path to raw field file
    spatial_field_paths: dict[str, str] = Field(default_factory=dict)
    # Distributions keyed by Observable.id -> list of samples
    distributions: dict[str, list[float]] = Field(default_factory=dict)
    # Flux observables keyed by Observable.id -> list of (t_s, flux_value)
    flux_time_series: dict[str, list[tuple[float, float]]] = Field(default_factory=dict)
    # Free metadata the plugin wants to surface
    notes: str = ""


class RunRecord(BaseModel):
    """The canonical record of one simulation run.

    Persisted as ``metadata/run.json`` under the run directory. Binds the
    IR, the skill file version, the assumption ledger, the resource usage,
    and the artifact list into one citable object.
    """

    run_id: str
    ir_id: str
    framework: str
    framework_version: str
    skill_file_version: str
    assumption_ledger_hash: str = Field(
        description="Content hash of the approved assumption ledger. Locks "
        "the run to the exact set of approved assumptions."
    )

    status: RunStatus = RunStatus.PENDING
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    started_at: Optional[datetime] = None
    ended_at: Optional[datetime] = None

    layout_root: Path
    artifacts: list[Artifact] = Field(default_factory=list)

    resource_usage: Optional[ResourceUsage] = None
    final_progress: Optional[ProgressReport] = None

    exit_code: Optional[int] = None
    failure_reason: Optional[str] = None

    extra: dict[str, Any] = Field(
        default_factory=dict,
        description="Plugin-specific extras (job IDs, container digests, ...).",
    )
